# The base image is the latest 8.x node (LTS) on alpine
FROM node:8.16.0-alpine@sha256:2d6ffd6ee67dcee6a6595805c903f411afdec773f935539b0752579818273eb8

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY install/package.json /usr/src/app/package.json
RUN npm install && npm cache clean --force
COPY . /usr/src/app

ENV NODE_ENV=production \
    daemon=false \
    silent=false

CMD ./nodebb start

# the default port for NodeBB is exposed outside the container
EXPOSE 4567
